#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    update-alternatives --install /usr/bin/x-www-browser \
        x-www-browser /usr/bin/little 80
    echo "Run sudo xdg-settings set default-web-browser little.desktop && sudo update-alternatives --config x-www-browser to set Little as your default browser."
fi